### ISSUE TITLE
[BUG] 댓글 삭제 시 자유 게시판 목록에 삭제된 댓글 수 반영이 안됩니다.

### ISSUE THREAD

**Issue by merong245** [SSAF-SOUND/ssaf-sound-be#299]
### 소개

댓글 추가 시, 자유 게시판 목록에서 반영이 되지만
삭제시에는 반영이 되지 않는 것으로 확인됩니다.

### 스크린샷

<img width="676" alt="image" src="https://github.com/SSAF-SOUND/ssaf-sound-be/assets/37497183/b12855ee-b1fe-4fbe-b036-8505c582f137">  

게시글 목록 화면 기존 댓글 2개
  
<img width="675" alt="image" src="https://github.com/SSAF-SOUND/ssaf-sound-be/assets/37497183/ae56543b-924c-404e-9488-ee565f632f99">

실제 게시글에 남아있는 댓글은 1개였고, 추가로 댓글 작성 후 삭제 시 해당 게시글 정보 (여기선 정상)
  

<img width="608" alt="image" src="https://github.com/SSAF-SOUND/ssaf-sound-be/assets/37497183/d3a2df08-cf74-4d14-9e61-b7351972baf8">  

새로고침 후 게시글 목록 화면에선 삭제된 댓글 2개 미반영으로 총 3개의 댓글 수 표기

**Comment by khs960616** [comment]
@merong245  감사합니당.

@jjuny0310

https://github.com/SSAF-SOUND/ssaf-sound-be/blob/dev/src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostElement.java
```java 
        this.content = post.getContent();
        this.likeCount = post.getLikes().size();
        this.commentCount = post.getComments().size();
```

likeCount post 조회시 where절 조건 추가 또는 엔티티 클래스에서 `@Where`로 soft delete 필터링 되도록 수정 필요

**Comment by jjuny0310** [comment]
확인했습니다!
